"""added item table

Revision ID: 10e21dab4e1b
Revises: 1c9faf8e96ab
Create Date: 2019-05-03 17:06:54.394879

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '10e21dab4e1b'
down_revision = '1c9faf8e96ab'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('item',
    sa.Column('item_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('price', sa.String(length=255), nullable=False),
    sa.Column('item_name', sa.String(length=255), nullable=False),
    sa.Column('category', sa.String(length=255), nullable=False),
    sa.Column('menu', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['menu'], ['menu.menu_id'], ),
    sa.PrimaryKeyConstraint('item_id'),
    sa.UniqueConstraint('item_id')
    )
    op.drop_constraint('menu_owner_fkey', 'menu', type_='foreignkey')
    op.drop_column('menu', 'owner')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('menu', sa.Column('owner', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('menu_owner_fkey', 'menu', 'owner', ['owner'], ['owner_id'])
    op.drop_table('item')
    # ### end Alembic commands ###
