"""change some names in Reservation table

Revision ID: 1eb93aafe1e2
Revises: 69252708237b
Create Date: 2019-04-25 10:52:57.522845

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1eb93aafe1e2'
down_revision = '69252708237b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reservation', sa.Column('customer_account', sa.Integer(), nullable=True))
    op.add_column('reservation', sa.Column('restaurant', sa.Integer(), nullable=True))
    op.drop_constraint('reservation_restaurant_reservation_fkey', 'reservation', type_='foreignkey')
    op.drop_constraint('reservation_customer_reservation_fkey', 'reservation', type_='foreignkey')
    op.create_foreign_key(None, 'reservation', 'restaurant', ['restaurant'], ['restaurant_id'])
    op.create_foreign_key(None, 'reservation', 'customer', ['customer_account'], ['customer_id'])
    op.drop_column('reservation', 'customer_reservation')
    op.drop_column('reservation', 'restaurant_reservation')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reservation', sa.Column('restaurant_reservation', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('reservation', sa.Column('customer_reservation', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'reservation', type_='foreignkey')
    op.drop_constraint(None, 'reservation', type_='foreignkey')
    op.create_foreign_key('reservation_customer_reservation_fkey', 'reservation', 'customer', ['customer_reservation'], ['customer_id'])
    op.create_foreign_key('reservation_restaurant_reservation_fkey', 'reservation', 'restaurant', ['restaurant_reservation'], ['restaurant_id'])
    op.drop_column('reservation', 'restaurant')
    op.drop_column('reservation', 'customer_account')
    # ### end Alembic commands ###
