"""empty message

Revision ID: 33f845d514be
Revises: a8fcf0237a6e
Create Date: 2019-04-08 20:57:09.268905

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '33f845d514be'
down_revision = 'a8fcf0237a6e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('customer', 'password_hash')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('customer', sa.Column('password_hash', sa.VARCHAR(length=80), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
