"""modified the tables

Revision ID: 3d4ef20b6c1a
Revises: 
Create Date: 2019-04-02 05:08:39.350795

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3d4ef20b6c1a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('blacklist_tokens',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('token', sa.String(length=500), nullable=False),
    sa.Column('blacklisted_on', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token')
    )
    op.create_table('owner',
    sa.Column('owner_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('firstname', sa.String(length=50), nullable=False),
    sa.Column('lastname', sa.String(length=50), nullable=False),
    sa.Column('contact_number', sa.String(length=11), nullable=True),
    sa.Column('gender', sa.String(length=6), nullable=False),
    sa.Column('password_hash', sa.String(length=80), nullable=True),
    sa.PrimaryKeyConstraint('owner_id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('restaurant',
    sa.Column('restaurant_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('restaurant_name', sa.String(length=30), nullable=False),
    sa.Column('restaurant_type', sa.String(length=30), nullable=False),
    sa.Column('bio', sa.String(length=200), nullable=False),
    sa.Column('locations', sa.String(length=200), nullable=False),
    sa.PrimaryKeyConstraint('restaurant_id'),
    sa.UniqueConstraint('restaurant_name')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('restaurant')
    op.drop_table('owner')
    op.drop_table('blacklist_tokens')
    # ### end Alembic commands ###
