"""added a new column on Response Table

Revision ID: 40697b861217
Revises: eda0df2591b7
Create Date: 2019-05-02 15:42:10.146520

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '40697b861217'
down_revision = 'eda0df2591b7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('response', sa.Column('restaurant', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'response', 'restaurant', ['restaurant'], ['restaurant_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'response', type_='foreignkey')
    op.drop_column('response', 'restaurant')
    # ### end Alembic commands ###
