"""added unique column on item

Revision ID: 67c66fe3cee3
Revises: ff709a41c503
Create Date: 2019-05-03 18:10:12.902385

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '67c66fe3cee3'
down_revision = 'ff709a41c503'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('item_item_id_key', 'item', type_='unique')
    op.create_unique_constraint(None, 'item', ['item_name'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'item', type_='unique')
    op.create_unique_constraint('item_item_id_key', 'item', ['item_id'])
    # ### end Alembic commands ###
