"""added a column

Revision ID: 69252708237b
Revises: b6e6cefb49e2
Create Date: 2019-04-25 10:15:36.379129

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '69252708237b'
down_revision = 'b6e6cefb49e2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reservation', sa.Column('reservee', sa.String(length=155), nullable=False))
    op.create_unique_constraint(None, 'reservation', ['reservee'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'reservation', type_='unique')
    op.drop_column('reservation', 'reservee')
    # ### end Alembic commands ###
