"""added Response model

Revision ID: 79498a65ab17
Revises: 01974d56b6fe
Create Date: 2019-05-01 20:42:52.422707

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '79498a65ab17'
down_revision = '01974d56b6fe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('response',
    sa.Column('response_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('owner_username', sa.String(length=155), nullable=False),
    sa.Column('response', sa.Boolean(), nullable=False),
    sa.Column('owner', sa.Integer(), nullable=True),
    sa.Column('reservation', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['owner'], ['owner.owner_id'], ),
    sa.ForeignKeyConstraint(['reservation'], ['reservation.reservation_id'], ),
    sa.PrimaryKeyConstraint('response_id'),
    sa.UniqueConstraint('owner_username')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('response')
    # ### end Alembic commands ###
