"""initial

Revision ID: 801a86b2e2cd
Revises: 
Create Date: 2019-05-08 15:58:45.479245

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '801a86b2e2cd'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('blacklist_tokens',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('token', sa.String(length=500), nullable=False),
    sa.Column('blacklisted_on', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token')
    )
    op.create_table('customer',
    sa.Column('customer_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=155), nullable=False),
    sa.Column('firstname', sa.String(length=50), nullable=False),
    sa.Column('lastname', sa.String(length=50), nullable=False),
    sa.Column('contact_number', sa.String(length=11), nullable=False),
    sa.Column('gender', sa.String(length=6), nullable=False),
    sa.Column('password_hash', sa.String(length=80), nullable=True),
    sa.PrimaryKeyConstraint('customer_id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('menu',
    sa.Column('menu_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('menu_name', sa.String(length=30), nullable=False),
    sa.PrimaryKeyConstraint('menu_id'),
    sa.UniqueConstraint('menu_name')
    )
    op.create_table('owner',
    sa.Column('owner_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=155), nullable=False),
    sa.Column('firstname', sa.String(length=50), nullable=False),
    sa.Column('lastname', sa.String(length=50), nullable=False),
    sa.Column('contact_number', sa.String(length=11), nullable=True),
    sa.Column('gender', sa.String(length=6), nullable=False),
    sa.Column('password_hash', sa.String(length=80), nullable=True),
    sa.PrimaryKeyConstraint('owner_id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('item',
    sa.Column('item_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('item_name', sa.String(length=255), nullable=False),
    sa.Column('price', sa.String(length=255), nullable=False),
    sa.Column('category', sa.String(length=255), nullable=False),
    sa.Column('menu', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['menu'], ['menu.menu_id'], ),
    sa.PrimaryKeyConstraint('item_id'),
    sa.UniqueConstraint('item_name')
    )
    op.create_table('restaurant',
    sa.Column('restaurant_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('restaurant_name', sa.String(length=30), nullable=False),
    sa.Column('restaurant_type', sa.String(length=30), nullable=False),
    sa.Column('bio', sa.String(length=200), nullable=False),
    sa.Column('locations', sa.String(length=200), nullable=False),
    sa.Column('owner', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['owner'], ['owner.owner_id'], ),
    sa.PrimaryKeyConstraint('restaurant_id'),
    sa.UniqueConstraint('restaurant_name')
    )
    op.create_table('reservation',
    sa.Column('reservation_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('reservee', sa.String(length=155), nullable=False),
    sa.Column('number_of_persons', sa.String(length=155), nullable=False),
    sa.Column('booking_date', sa.DateTime(), nullable=False),
    sa.Column('customer_account', sa.Integer(), nullable=True),
    sa.Column('restaurant', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['customer_account'], ['customer.customer_id'], ),
    sa.ForeignKeyConstraint(['restaurant'], ['restaurant.restaurant_id'], ),
    sa.PrimaryKeyConstraint('reservation_id'),
    sa.UniqueConstraint('reservee')
    )
    op.create_table('response',
    sa.Column('response_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('owner_username', sa.String(length=155), nullable=False),
    sa.Column('response', sa.Boolean(), nullable=False),
    sa.Column('message', sa.String(length=300), nullable=True),
    sa.Column('owner', sa.Integer(), nullable=True),
    sa.Column('reservation', sa.Integer(), nullable=True),
    sa.Column('restaurant', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['owner'], ['owner.owner_id'], ),
    sa.ForeignKeyConstraint(['reservation'], ['reservation.reservation_id'], ),
    sa.ForeignKeyConstraint(['restaurant'], ['restaurant.restaurant_id'], ),
    sa.PrimaryKeyConstraint('response_id'),
    sa.UniqueConstraint('owner_username')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('response')
    op.drop_table('reservation')
    op.drop_table('restaurant')
    op.drop_table('item')
    op.drop_table('owner')
    op.drop_table('menu')
    op.drop_table('customer')
    op.drop_table('blacklist_tokens')
    # ### end Alembic commands ###
