"""added reservations table

Revision ID: b52b02cb558b
Revises: 44f286a331cd
Create Date: 2019-04-16 19:21:01.272465

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b52b02cb558b'
down_revision = '44f286a331cd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reservation',
    sa.Column('reservation_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('pax_number', sa.String(length=155), nullable=False),
    sa.Column('booking_date', sa.DateTime(), nullable=False),
    sa.Column('booking_status', sa.String(), nullable=False),
    sa.Column('customer_reservation', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['customer_reservation'], ['customer.customer_id'], ),
    sa.PrimaryKeyConstraint('reservation_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('reservation')
    # ### end Alembic commands ###
