"""deleted a column

Revision ID: b6e6cefb49e2
Revises: 6a97a0a558ed
Create Date: 2019-04-25 09:27:15.274039

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b6e6cefb49e2'
down_revision = '6a97a0a558ed'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('reservation', 'booking_status')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reservation', sa.Column('booking_status', sa.VARCHAR(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
