"""empty message

Revision ID: e0331bfe049e
Revises: 33f845d514be
Create Date: 2019-04-08 22:08:54.269504

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e0331bfe049e'
down_revision = '33f845d514be'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('customer', sa.Column('password_hash', sa.String(length=80), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('customer', 'password_hash')
    # ### end Alembic commands ###
