"""added a column in Response table

Revision ID: eda0df2591b7
Revises: 79498a65ab17
Create Date: 2019-05-01 20:48:37.114178

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eda0df2591b7'
down_revision = '79498a65ab17'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('response', sa.Column('message', sa.String(length=300), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('response', 'message')
    # ### end Alembic commands ###
