"""removed some columns on menu table

Revision ID: ff709a41c503
Revises: 10e21dab4e1b
Create Date: 2019-05-03 17:49:39.805444

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ff709a41c503'
down_revision = '10e21dab4e1b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'item', ['item_id'])
    op.drop_column('menu', 'locations')
    op.drop_column('menu', 'menu_type')
    op.drop_column('menu', 'bio')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('menu', sa.Column('bio', sa.VARCHAR(length=200), autoincrement=False, nullable=False))
    op.add_column('menu', sa.Column('menu_type', sa.VARCHAR(length=30), autoincrement=False, nullable=False))
    op.add_column('menu', sa.Column('locations', sa.VARCHAR(length=200), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'item', type_='unique')
    # ### end Alembic commands ###
